spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivre
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
